[package]
name = "traits"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "write"
path = "src/write.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
