[package]
name = "smart_pointers"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "box"
path = "src/box.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
