[package]
name = "multi_owner"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rc"
path = "src/rc.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
